name: API Test

on:
  workflow_dispatch: # Manual trigger

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci # Ensures a clean install of all dependencies, including Cypress

      - name: Verify Cypress Installation
        run: npx cypress verify # Checks if Cypress is installed correctly

      - name: Run API Tests
        run: npx cypress run --spec "cypress/e2e/dummyJsonAPI.cy.js"
