name: Load Test with k6

on:
  workflow_dispatch: # Manual trigger

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug - List Files
        run: ls -R # Check if loadTest.js exists

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: ./loadtest/loadtest.js
