name: Load Test with k6

on:
  workflow_dispatch: # Manual trigger

jobs:
  run-load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          sudo apt update
          sudo apt install -y curl git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install k6
        run: |
          brew install k6
          k6 version  # Check if installation was successful

      - name: Verify Load Test File
        run: ls -l loadtest/ # Debugging step to check if the file exists

      - name: Run Load Test
        run: k6 run loadtest/loadTest.js
